/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeleteApiDocumentsIdMutationResponse, DeleteApiDocumentsIdPathParams } from "./ delete_api-documents-id .ts";
import type { GetApiDocumentsQueryResponse } from "./ get_api-documents .ts";
import type { GetApiDocumentsIdQueryResponse, GetApiDocumentsIdPathParams } from "./ get_api-documents-id .ts";
import type { GetHealthQueryResponse } from "./ get_health .ts";
import type { PatchApiDocumentsIdMutationResponse, PatchApiDocumentsIdPathParams } from "./ patch_api-documents-id .ts";
import type { PostApiConvertPdfToDocxMutationResponse } from "./ post_api-convert-pdf-to-docx .ts";
import type { PostApiDocumentsMutationResponse } from "./ post_api-documents .ts";
import type { PostApiImportPdfEditableMutationResponse } from "./ post_api-import-pdf-editable .ts";
import type { PostApiImportPdfOptionsMutationResponse } from "./ post_api-import-pdf-options .ts";
import type { PostApiOcrImageMutationResponse } from "./ post_api-ocr-image .ts";
import type { PostApiSyncPushMutationResponse } from "./ post_api-sync-push .ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetHealthUrl() {
  const res = { method: 'GET', url: `/health` as const }
  return res
}

/**
 * {@link /health}
 */
export async function getHealth(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetHealthQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetHealthUrl().url.toString(), ... requestConfig })
  return res.data
}

function getGetApiDocumentsUrl() {
  const res = { method: 'GET', url: `/api/documents` as const }
  return res
}

/**
 * {@link /api/documents}
 */
export async function getApiDocuments(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetApiDocumentsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiDocumentsUrl().url.toString(), ... requestConfig })
  return res.data
}

function getPostApiDocumentsUrl() {
  const res = { method: 'POST', url: `/api/documents` as const }
  return res
}

/**
 * {@link /api/documents}
 */
export async function postApiDocuments(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PostApiDocumentsMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPostApiDocumentsUrl().url.toString(), ... requestConfig })
  return res.data
}

function getGetApiDocumentsIdUrl(id: GetApiDocumentsIdPathParams["id"]) {
  const res = { method: 'GET', url: `/api/documents/${id}` as const }
  return res
}

/**
 * {@link /api/documents/:id}
 */
export async function getApiDocumentsId(id: GetApiDocumentsIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetApiDocumentsIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiDocumentsIdUrl(id).url.toString(), ... requestConfig })
  return res.data
}

function getPatchApiDocumentsIdUrl(id: PatchApiDocumentsIdPathParams["id"]) {
  const res = { method: 'PATCH', url: `/api/documents/${id}` as const }
  return res
}

/**
 * {@link /api/documents/:id}
 */
export async function patchApiDocumentsId(id: PatchApiDocumentsIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PatchApiDocumentsIdMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "PATCH", url : getPatchApiDocumentsIdUrl(id).url.toString(), ... requestConfig })
  return res.data
}

function getDeleteApiDocumentsIdUrl(id: DeleteApiDocumentsIdPathParams["id"]) {
  const res = { method: 'DELETE', url: `/api/documents/${id}` as const }
  return res
}

/**
 * {@link /api/documents/:id}
 */
export async function deleteApiDocumentsId(id: DeleteApiDocumentsIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteApiDocumentsIdMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteApiDocumentsIdUrl(id).url.toString(), ... requestConfig })
  return res.data
}

function getPostApiSyncPushUrl() {
  const res = { method: 'POST', url: `/api/sync/push` as const }
  return res
}

/**
 * {@link /api/sync/push}
 */
export async function postApiSyncPush(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PostApiSyncPushMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPostApiSyncPushUrl().url.toString(), ... requestConfig })
  return res.data
}

function getPostApiImportPdfEditableUrl() {
  const res = { method: 'POST', url: `/api/import/pdf/editable` as const }
  return res
}

/**
 * {@link /api/import/pdf/editable}
 */
export async function postApiImportPdfEditable(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PostApiImportPdfEditableMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPostApiImportPdfEditableUrl().url.toString(), ... requestConfig })
  return res.data
}

function getPostApiConvertPdfToDocxUrl() {
  const res = { method: 'POST', url: `/api/convert/pdf-to-docx` as const }
  return res
}

/**
 * {@link /api/convert/pdf-to-docx}
 */
export async function postApiConvertPdfToDocx(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PostApiConvertPdfToDocxMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPostApiConvertPdfToDocxUrl().url.toString(), ... requestConfig })
  return res.data
}

function getPostApiOcrImageUrl() {
  const res = { method: 'POST', url: `/api/ocr/image` as const }
  return res
}

/**
 * {@link /api/ocr/image}
 */
export async function postApiOcrImage(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PostApiOcrImageMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPostApiOcrImageUrl().url.toString(), ... requestConfig })
  return res.data
}

function getPostApiImportPdfOptionsUrl() {
  const res = { method: 'POST', url: `/api/import/pdf/options` as const }
  return res
}

/**
 * {@link /api/import/pdf/options}
 */
export async function postApiImportPdfOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PostApiImportPdfOptionsMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPostApiImportPdfOptionsUrl().url.toString(), ... requestConfig })
  return res.data
}