import { Template } from '@/types';
import { getDemoManualContent } from './demo-documents.ts';

const EMPTY_SHEET = JSON.stringify({
  data: Array.from({ length: 50 }, () => Array(26).fill(null)),
  colHeaders: Array.from({ length: 26 }, (_, i) => String.fromCharCode(65 + i)),
  rowCount: 50,
  colCount: 26,
});

const EMPTY_DOC = JSON.stringify({
  type: 'doc',
  content: [{ type: 'paragraph', content: [] }],
});

export const TEMPLATES: Template[] = [
  {
    id: 'tpl-report',
    name: 'Relatório de Projeto',
    description: 'Estrutura completa para relatórios de status (PMBOK)',
    type: 'text',
    thumbnail: '📊',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Relatório de Status do Projeto' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: 'Projeto: [nome] | Período: [data início] a [data fim] | Responsável: [nome] | Data do relatório: [data]' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '1. Resumo Executivo' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Visão geral em 2–3 linhas: situação atual do projeto, principais conquistas no período e alertas críticos (se houver).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '2. Indicadores de Desempenho (Status)' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Escopo: ' }, { type: 'text', text: '[Verde / Amarelo / Vermelho] — Justificativa breve.' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Cronograma: ' }, { type: 'text', text: '[Verde / Amarelo / Vermelho] — Aderência ao plano; atrasos se houver.' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Custo/Orçamento: ' }, { type: 'text', text: '[Verde / Amarelo / Vermelho] — Situação em relação ao previsto.' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Qualidade: ' }, { type: 'text', text: '[Verde / Amarelo / Vermelho] — Entregas e testes.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '3. Entregas Realizadas no Período' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Entregável 1] — [breve descrição]' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Entregável 2] — [breve descrição]' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '4. Riscos e Bloqueios' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Riscos identificados (probabilidade/impacto) e ações de mitigação. Bloqueios atuais e quem está tratando.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '5. Desvios e Mudanças' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Desvios em relação ao plano (escopo, prazo, custo) e mudanças aprovadas ou em análise.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '6. Próximos Passos (Plano de Ação)' }] },
        { type: 'orderedList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Ação] — Responsável: [nome] — Prazo: [data]' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Ação] — Responsável: [nome] — Prazo: [data]' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '7. Lições Aprendidas (opcional)' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'O que funcionou bem e o que pode ser melhorado no próximo período.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '8. Conclusão' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Síntese e expectativa para o próximo ciclo de reporte.' }] },
      ],
    }),
  },
  {
    id: 'tpl-minutes',
    name: 'Ata de Reunião',
    description: 'Registro formal com objetivo, pauta, decisões e ações (SMART)',
    type: 'text',
    thumbnail: '📝',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Ata de Reunião' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Título/Assunto: ' }, { type: 'text', text: '[ex: Acompanhamento Sprint 5]' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Data e horário: ' }, { type: 'text', text: '[dd/mm/aaaa] — [início] às [fim]' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Local: ' }, { type: 'text', text: '[sala / link da reunião online]' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Objetivo da reunião: ' }, { type: 'text', text: 'Uma frase descrevendo o propósito (ex: alinhar escopo da entrega X).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Participantes' }] },
        { type: 'paragraph', content: [{ type: 'text', text: '[Nome 1] — [Papel/Área]; [Nome 2] — [Papel/Área]. Facilitador/Redator: [nome].' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Pauta' }] },
        { type: 'orderedList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Ponto 1 — [tema]' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Ponto 2 — [tema]' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Ponto 3 — [tema]' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Discussões e Decisões' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Ponto 1 — [tema]: ' }, { type: 'text', text: 'Resumo da discussão. Decisão: [o que foi decidido].' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Ponto 2 — [tema]: ' }, { type: 'text', text: 'Resumo. Decisão: [o que foi decidido].' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Ações Definidas (SMART)' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: 'Especificar: O quê | Quem | Quando | Como verificar conclusão.' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Ação] — Responsável: [nome] — Prazo: [data] — Verificação: [critério]' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Ação] — Responsável: [nome] — Prazo: [data] — Verificação: [critério]' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Pendências para próxima reunião' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Itens não esgotados ou que dependem de informação externa.' }] },
        { type: 'paragraph', content: [] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Próxima reunião: ' }, { type: 'text', text: '[data e hora].' }] },
      ],
    }),
  },
  {
    id: 'tpl-spec-func',
    name: 'Especificação Funcional',
    description: 'Estrutura completa para especificação (requisitos, critérios de aceite, RNF)',
    type: 'text',
    thumbnail: '📋',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Especificação Funcional' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: 'Projeto: [nome] | Módulo/Sistema: [nome] | Versão: 1.0 | Data: [data] | Autor: [nome]' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Histórico de Revisões' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'v1.0 — [data] — [autor] — Versão inicial. (Manter registro de alterações.)' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '1. Visão Geral' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Contexto do negócio, problema a ser resolvido e resumo do sistema ou módulo (SAP, .NET, React, Flutter, etc.).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '2. Objetivos' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Objetivo de negócio 1' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Objetivo de negócio 2' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '3. Partes Interessadas (Stakeholders)' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Quem solicita, quem usa, quem aprova: Papel — Nome/Área — Responsabilidade.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '4. Escopo' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Incluído: ' }, { type: 'text', text: 'funcionalidades e limites dentro do escopo desta especificação.' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Fora do escopo: ' }, { type: 'text', text: 'explicitamente excluído para evitar ambiguidade.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '5. Requisitos Funcionais' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: 'Formato sugerido: ID | Descrição | Prioridade (M/F/B) | Critérios de aceite.' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'RF01 — [Descrição clara e testável]. Prioridade: Must. Aceite: [condição 1]; [condição 2].' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'RF02 — [Descrição]. Prioridade: Should. Aceite: [critérios].' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '6. Requisitos Não Funcionais' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Performance, segurança, usabilidade, disponibilidade, compatibilidade (navegadores, SAP release, etc.).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '7. Regras de Negócio' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'RN01 — [Condição] então [ação/resultado].' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'RN02 — [Regra de validação ou cálculo].' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '8. Casos de Uso / User Stories' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Como [ator], quero [ação] para [benefício]. Critérios de aceite: Dado... Quando... Então...' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '9. Fluxos e Telas (Resumo)' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Fluxo principal em passos; referência a protótipos ou wireframes em anexo.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '10. Glossário' }] },
        { type: 'paragraph', content: [{ type: 'text', text: '[Termo] — [Definição]. [Sigla] — [Significado].' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '11. Referências e Anexos' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Documentos de negócio, diagramas, protótipos, interfaces de sistemas (APIs, transações SAP).' }] },
      ],
    }),
  },
  {
    id: 'tpl-api-doc',
    name: 'Documentação de API',
    description: 'Documentação REST completa (versionamento, auth, erros, exemplos)',
    type: 'text',
    thumbnail: '🔌',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Documentação de API' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Nome do serviço: ' }, { type: 'text', text: '[ex: API de Pedidos / Integração SAP]' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Versão da API: ' }, { type: 'text', text: 'v1 (versionamento semântico recomendado)' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Base URL: ' }, { type: 'text', text: 'https://api.exemplo.com/v1' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Formato: ' }, { type: 'text', text: 'JSON. Charset: UTF-8.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '1. Visão Geral' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Propósito da API, cenários de uso (integração .NET, React, Flutter, SAP, etc.) e convenções gerais.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '2. Autenticação e Autorização' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Método: Bearer (JWT) / API Key / OAuth 2.0. Como obter credenciais, header (ex: Authorization: Bearer &lt;token&gt;), tempo de vida do token.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '3. Headers Obrigatórios e Opcionais' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Content-Type: application/json; Accept: application/json; X-Request-ID (rastreio); idioma/localização se aplicável.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '4. Rate Limit e Throttling' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Limite de requisições por minuto/hora; headers de resposta (X-RateLimit-Remaining, Retry-After); comportamento em 429.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '5. Endpoints' }] },
        { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'GET /recurso' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Descrição: ' }, { type: 'text', text: 'Lista recursos com paginação e filtros.' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Parâmetros (query): ' }, { type: 'text', text: 'page, limit, sort, filtros. Tipo e obrigatoriedade.' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Respostas: ' }, { type: 'text', text: '200 OK — body; 400 Bad Request; 401 Unauthorized; 500 Internal Error.' }] },
        { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'POST /recurso' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Descrição: ' }, { type: 'text', text: 'Criação de recurso.' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Body (JSON): ' }, { type: 'text', text: 'campos obrigatórios e opcionais, tipos, validações, exemplos.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '6. Modelo de Erro Padronizado' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Estrutura: code, message, details (lista de erros de validação), requestId, timestamp.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '7. Códigos HTTP e de Negócio' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '400 — Requisição inválida (payload ou parâmetros)' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '401 — Não autenticado' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '403 — Sem permissão' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '404 — Recurso não encontrado' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '409 — Conflito (ex: duplicidade)' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '429 — Rate limit excedido' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '500 — Erro interno (incluir requestId para suporte)' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '8. Exemplos (cURL e Response)' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Exemplo de request (cURL ou snippet) e exemplo de response JSON (sucesso e erro).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '9. Changelog da API' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Registro de alterações por versão: endpoints novos, depreciados, breaking changes.' }] },
      ],
    }),
  },
  {
    id: 'tpl-manual',
    name: 'Manual de Uso',
    description: 'Manual completo com índice, convenções e troubleshooting',
    type: 'text',
    thumbnail: '📖',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Manual de Uso' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Sistema/Produto: ' }, { type: 'text', text: '[nome]' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Versão do documento: ' }, { type: 'text', text: '1.0 | Data: [data]' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Índice' }] },
        { type: 'paragraph', content: [{ type: 'text', text: '1. Introdução | 2. Público-alvo e pré-requisitos | 3. Acesso ao sistema | 4. Funcionalidades (por módulo/tela) | 5. Fluxos principais | 6. Solução de problemas | 7. Contato e suporte | 8. Histórico de revisões' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '1. Introdução' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Objetivo do sistema, o que o usuário pode realizar e contexto de uso (ex: módulo SAP, aplicação web .NET/React/Flutter).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '2. Público-alvo e Pré-requisitos' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Público-alvo: ' }, { type: 'text', text: 'perfil dos usuários (operador, analista, administrador).' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Navegador compatível (Chrome, Edge, etc.) ou cliente SAP' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Acesso à rede e perfil de usuário concedido' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Resolução mínima de tela (se aplicável)' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '3. Convenções do Manual' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Significado de ícones ou destaques usados no documento (ex: [Atenção], [Dica], nomes de botões entre aspas, caminhos de menu em negrito).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '4. Acesso ao Sistema' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'URL ou transação de acesso, tela de login e primeiro acesso (senha temporária, alteração obrigatória).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '5. Funcionalidades (por Módulo/Tela)' }] },
        { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: '5.1 [Nome da funcionalidade ou tela]' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Objetivo desta tela/função em uma frase.' }] },
        { type: 'orderedList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Passo 1: acesse o menu [caminho] ou clique em [botão].' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Passo 2: preencha os campos obrigatórios [lista].' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Passo 3: confirme com [ação]. Inclua captura de tela se necessário.' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '6. Fluxos Principais' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Descrição dos fluxos de negócio mais usados (ex: cadastrar pedido, aprovar solicitação), com referência às seções acima.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '7. Solução de Problemas (FAQ / Troubleshooting)' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Problema: ' }, { type: 'text', text: '[mensagem de erro ou sintoma]. Causa provável: [breve]. Solução: [passos].' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Problema: ' }, { type: 'text', text: '[outro caso]. Solução: [passos].' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '8. Contato e Suporte' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'E-mail, telefone ou canal de abertura de chamado; horário de atendimento; informações úteis para o suporte (sistema, versão, usuário).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '9. Histórico de Revisões do Manual' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Data | Versão | Alteração | Autor.' }] },
      ],
    }),
  },
  {
    id: 'tpl-demo-manual',
    name: 'Manual de Demonstração',
    description: 'Documento de teste com formatação, imagens e paginação para validar exportação PDF/DOCX',
    type: 'text',
    thumbnail: '📄',
    content: getDemoManualContent(),
  },
  {
    id: 'tpl-proposal',
    name: 'Proposta Técnica / Escopo',
    description: 'Proposta alinhada a PMBOK (stakeholders, riscos, critérios de aceite)',
    type: 'text',
    thumbnail: '📑',
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Proposta Técnica e Escopo de Projeto' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: 'Cliente: [nome] | Projeto: [nome] | Data: [data] | Versão: 1.0' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '1. Contexto e Justificativa' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Situação atual do cliente, dor ou oportunidade, e por que este projeto é necessário (alineado ao negócio).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '2. Objetivos' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Objetivo específico 1 (mensurável quando possível)' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Objetivo específico 2' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '3. Partes Interessadas (Stakeholders)' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Patrocinador, gestor do projeto, usuários-chave, áreas impactadas; papel e nível de envolvimento (PMBOK).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '4. Escopo' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Incluído no escopo: ' }, { type: 'text', text: 'entregas, funcionalidades e limites claros.' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Explicitamente fora do escopo: ' }, { type: 'text', text: 'o que não será feito (evita expectativas incorretas).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '5. Stack e Tecnologias' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'SAP ABAP (release), .NET (versão), React/Flutter, APIs, banco de dados, ferramentas de integração; justificativa breve se relevante.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '6. Entregas e Critérios de Aceite' }] },
        { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: 'Para cada entregável: descrição + critério de aceite (como será validado).' }] },
        { type: 'bulletList', content: [
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Entregável 1 — [descrição]. Aceite: [condição de validação].' }] }] },
          { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Entregável 2 — [descrição]. Aceite: [condição].' }] }] },
        ]},
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '7. Cronograma (Macro)' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Fases (ex: levantamento, desenvolvimento, testes, implantação) com datas de início e fim; marcos principais (milestones).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '8. Premissas' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Premissas técnicas (ambiente, acesso a sistemas), de negócio (disponibilidade do cliente, dados) e de recurso.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '9. Restrições' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Prazo fixo, orçamento, dependências de terceiros, janelas de implantação, conformidade (LGPD, segurança).' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '10. Riscos Iniciais' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Riscos identificados (ex: disponibilidade de ambiente SAP) com probabilidade/impacto e mitigação sugerida.' }] },
        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '11. Aprovações' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Cliente: _______________________ Data: ______. Consultoria: _______________________ Data: ______.' }] },
      ],
    }),
  },
  {
    id: 'tpl-backlog',
    name: 'Cronograma / Backlog de Projeto',
    description: 'Backlog com prioridade, aceite e dependências (PMBOK/Scrum)',
    type: 'spreadsheet',
    thumbnail: '📅',
    content: JSON.stringify({
      data: [
        ['ID', 'Tipo', 'Atividade / User Story', 'Critérios de Aceite', 'Responsável', 'Sprint/Fase', 'Prioridade', 'Status', 'Est. (h)', 'Dependência', 'Observações'],
        ['1', 'Story', 'Como usuário quero fazer login para acessar o sistema', 'Login com usuário/senha; bloqueio após 3 tentativas', '', 'Sprint 1', 'Alta', 'A fazer', '', '', ''],
        ['2', 'Task', 'Integração API de usuários (GET/POST)', 'Documentação de API atualizada; testes automatizados', '', 'Sprint 1', 'Alta', 'A fazer', '', '1', ''],
        ['3', 'Story', 'Relatório SAP: listagem de pedidos por centro', 'Filtros; exportação Excel; performance < 5s', '', 'Sprint 2', 'Média', 'A fazer', '', '1', 'Transação Z ou Fiori'],
        ['4', 'Task', 'Desenvolvimento tela React de cadastro', 'Validações; acessibilidade; responsivo', '', 'Sprint 2', 'Média', 'A fazer', '', '2', ''],
        ['5', 'Task', 'Testes UAT com cliente', 'Cenários aprovados; evidências documentadas', '', 'Sprint 3', 'Alta', 'A fazer', '', '3,4', ''],
        ['6', 'Task', 'Documentação técnica e manual de uso', 'Revisão aprovada pelo líder técnico', '', 'Sprint 3', 'Média', 'A fazer', '', '5', ''],
        ['7', 'Bug', 'Correção: cálculo de totais na tela X', 'Cenários de teste passando', '', 'Sprint 3', 'Alta', 'A fazer', '', '', ''],
      ],
      colHeaders: ['A','B','C','D','E','F','G','H','I','J','K'],
      rowCount: 50,
      colCount: 11,
    }),
  },
  {
    id: 'tpl-entregas',
    name: 'Lista de Entregas',
    description: 'Entregáveis com critérios de aceite e dependências (PMBOK)',
    type: 'spreadsheet',
    thumbnail: '📦',
    content: JSON.stringify({
      data: [
        ['ID', 'Entregável', 'Projeto', 'Critérios de Aceite', 'Responsável', 'Data Prev.', 'Data Real', 'Status', 'Dependência', 'Observações'],
        ['1', 'Especificação funcional aprovada', '', 'Aprovação formal do cliente; baseline de escopo', '', '', '', 'Pendente', '', ''],
        ['2', 'Ambiente de desenvolvimento disponível', '', 'Acesso SAP/.NET; CI/CD configurado', '', '', '', 'Pendente', '', ''],
        ['3', 'Módulo de pedidos (backend + frontend)', '', 'Requisitos RF01-RF05 atendidos; testes unitários', '', '', '', 'Pendente', '1,2', ''],
        ['4', 'Integração com sistema legado', '', 'Fluxo end-to-end validado; documentação API', '', '', '', 'Pendente', '3', ''],
        ['5', 'Testes de integração e UAT', '', 'Plano de testes executado; bugs críticos zerados', '', '', '', 'Pendente', '3,4', ''],
        ['6', 'Manual de uso e documentação técnica', '', 'Revisão aprovada; publicada na wiki/confluence', '', '', '', 'Pendente', '5', ''],
        ['7', 'Deploy em homologação', '', 'Smoke test OK; acesso liberado ao cliente', '', '', '', 'Pendente', '5,6', ''],
      ],
      colHeaders: ['A','B','C','D','E','F','G','H','I','J'],
      rowCount: 40,
      colCount: 10,
    }),
  },
];

export const EMPTY_TEMPLATES = {
  text: EMPTY_DOC,
  spreadsheet: EMPTY_SHEET,
};
